source 'https://cdn.cocoapods.org/'
platform :ios, '14.0'

target 'EagleDemo' do
    pod 'Eagle-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/eagle/v1.0-ios/binding/ios/Eagle-iOS.podspec'
    pod 'ios-voice-processor', '~> 1.0.3'
end
