source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'EagleAppTest' do
    pod 'Eagle-iOS', '~> 1.0.0'
end

target 'EagleAppTestUITests' do
    pod 'Eagle-iOS', '~> 1.0.0'
end

target 'PerformanceTest' do
    pod 'Eagle-iOS', '~> 1.0.0'
end
