source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'EagleAppTest' do
    pod 'Eagle-iOS', '~> 0.1.0'
end

target 'EagleAppTestUITests' do
    pod 'Eagle-iOS', '~> 0.1.0'
end

target 'PerformanceTest' do
    pod 'Eagle-iOS', '~> 0.1.0'
end
