name: Android Performance

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'

defaults:
  run:
    working-directory: binding/android/EagleTestApp

jobs:
  build:
    name: Run Android Speed Tests on AppCenter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [single-android, 32bit-android]
        include:
        - device: single-android
          enrollPerformanceThresholdSec: 0.6
          procPerformanceThresholdSec: 0.6
        - device: 32bit-android
          enrollPerformanceThresholdSec: 5.5
          procPerformanceThresholdSec: 5.5

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Inject Number of Iterations
      run: echo numTestIterations="20" >> local.properties

    - name: Inject Enroll Performance Threshold
      run: echo enrollPerformanceThresholdSec="${{ matrix.enrollPerformanceThresholdSec }}" >> local.properties

    - name: Inject Proc Performance Threshold
      run: echo procPerformanceThresholdSec="${{ matrix.procPerformanceThresholdSec }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleDebugAndroidTest

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Eagle-Android"
        --devices "Picovoice/${{ matrix.device }}"
        --app-path eagle-test-app/build/outputs/apk/debug/eagle-test-app-debug.apk
        --test-series "eagle-android"
        --locale "en_US"
        --build-dir eagle-test-app/build/outputs/apk/androidTest/debug
