name: iOS Demos

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'demo/ios/EagleDemo/**'
      - '.github/workflows/ios-demos.yml'
  pull_request:
    branches: [ main, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/ios/EagleDemo/**'
      - '.github/workflows/ios-demos.yml'

defaults:
  run:
    working-directory: demo/ios/EagleDemo

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: xcrun xcodebuild build
          -configuration Debug
          -project EagleDemo.xcodeproj
          -sdk iphoneos
          -scheme EagleDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO