name: Python Performance

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/python-perf.yml'
      - 'binding/python/__init__.py'
      - 'binding/python/_eagle.py'
      - 'binding/python/_util.py'
      - 'binding/python/test_eagle_perf.py'
      - 'lib/common/**'
      - 'lib/jetson/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/audio_samples/*.wav'
  pull_request:
    branches: [main, 'v[0-9]+.[0-9]+']
    paths:
      - '.github/workflows/python-perf.yml'
      - 'binding/python/__init__.py'
      - 'binding/python/_eagle.py'
      - 'binding/python/_util.py'
      - 'binding/python/test_eagle_perf.py'
      - 'lib/common/**'
      - 'lib/jetson/**'
      - 'lib/linux/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/audio_samples/*.wav'

defaults:
  run:
    working-directory: binding/python

jobs:
  perf-github-hosted:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Pre-build dependencies
      run: python -m pip install --upgrade pip

    - name: Build dependencies
      run: |
        pip install wheel && python setup.py sdist bdist_wheel && pip install pip install dist/*.whl

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test
      run: >
        python3 test_eagle_perf.py 
        --access-key ${{secrets.PV_VALID_ACCESS_KEY}} 
        --num-test-iterations 20
        --profiler-performance-threshold-sec 0.6
        --recognizer-performance-threshold-sec 0.6